[package]
name = "bitburst"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"
ndarray = "0.16.1"

[[bench]]
name = "add"
harness = false

[profile.release]
lto = "fat" # Or "thin"
codegen-units = 1
